collectors:
  system: true
  hardware: true
  network: true
  services: true
  performance: true

advanced_checks:
  network_ping_hosts:
    - 8.8.8.8
    - google.com
    - azure.com
  services_to_monitor:
    - ssh
    - docker
    - nginx
    - mysql
    - postgresql